config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  resources :users, except: [:new, :create, :destroy] do
    collection do
      get '/confirm_unsubscribe' => 'users#unsubscribe', as: '/confirm_unsubscribe'
      patch '/withdraw' => 'users#withdraw', as: '/withdraw'
      get :interests
    end
     member do
      get :following, :followers, :timeline
    end

  end

  resources :relationships, only: [:create, :index, :destroy]

  resources :articles do
    resources :comments, only: [:create, :destroy]
    resources :interests, only: [:create, :destroy]
    resource :visits, only: [:create, :destroy]
    collection do
      get :search_result
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :body, presence: true
  validates :body, length: { maximum: 150 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    @comment = current_user.comments.new(comment_params)
    @comment.article_id = @article.id
    @comment.save
    render :index
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = Comment.find_by(id: params[:id], article_id: params[:article_id])
    @comment.destroy
    render :index
  end

 private

  def comment_params
    params.require(:comment).permit(:user_id, :article_id, :body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_error.html.erb
<% if @comment.errors.any? %>
<div class="error_message alert">
    <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/comments/_index.html.erb
<p>コメント件数：<%= comments.count %></p>
<hr />
  <% comments.each do |comments| %>
  <p class="article-body">
    <%= link_to comments.user.name, user_path(comments.user)%>
  </p>
  <p class="article-body">
    <%= comments.body %>
  </p>
  <p class="article-body posted-dates">
    <%= l comments.created_at, format: :long %>
    <% if comments.user == current_user %>
      <%= link_to article_comment_path(comments.article.id, comments.id), method: :delete, remote: true, data: {confirm: "コメントを削除しますか？"} do %>
        <i class="fas fa-trash-alt" style="color: crimson;"></i>
      <% end %>
    <% end %>
  </p>
<hr />
  <% end %>

app/views/comments/_new.html.erb
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with(model:[article, comment], url: article_comments_path(@article) ) do |f| %>
    <%= f.text_area :body, rows:'5',placeholder: "コメントをする（150文字以内）",maxlength:"150", class:"form-control" %>
    <%= f.submit "送信する", class:"btn btn-success" %>
  <% end %>

app/views/comments/index.js.erb
<!--コメント投稿 ---->
$("#comments").html("<%= j(render 'index', comments: @article.comments) %>")
$("#error_explanation").html("<%= j(render 'error', { comment: @comment }) %>")
$("textarea").val('')