config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  resources :users, except: [:new, :create, :destroy] do
    collection do
      get '/confirm_unsubscribe' => 'users#unsubscribe', as: '/confirm_unsubscribe'
      patch '/withdraw' => 'users#withdraw', as: '/withdraw'
      get :interests
    end
     member do
      get :following, :followers, :timeline
    end

  end

  resources :relationships, only: [:create, :index, :destroy]

  resources :articles do
    resources :comments, only: [:create, :destroy]
    resources :interests, only: [:create, :destroy]
    resource :visits, only: [:create, :destroy]
    collection do
      get :search_result
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :interests, dependent: :destroy
  has_many :visits, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :address, presence: true
  validates :post_img, presence: true

  attachment :post_img

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
    @user = current_user
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    @user = current_user
    if @article.save
      redirect_to article_path(@article)
    else
      render new_article_path
    end
  end

  def index
    @articles = Article.page(params[:page]).reverse_order
  end

  def search_result
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.page(params[:page])
    if user_signed_in?
      @interest = Interest.find_by(user_id: current_user.id, article_id: @article.id)
      @visit = Visit.find_by(user_id: current_user.id, article_id: @article.id)
    end
    @comment = Comment.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:user_id, :title, :body, :post_img, :rate, :address, :latitude, :longitude)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article_detail.html.erb
  <% if @article.errors.any? %>
    <div class="article-new-field alert">
      <ul><% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_with model:@article, local:true do |f| %>
    <div class="article-new-field">
      <label class="article-new-detail">店名</label>
        <div class="article-new-detail">
          <%= f.text_field :title, class:"form-control" %>
        </div>
    </div>
    <div class="article-new-field">
      <label class="article-new-detail">住所</label>
        <div class="article-new-detail">
          <%= f.text_field :address, class:"form-control" %>
        </div>
    </div>
    <div class="article-new-field">
      <label class="article-new-detail">評価</label>
      <div class="article-new-detail", id="star">

        <script>
          $('#star').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'article[rate]',
            half: true,
          });
          </script>
      </div>
    </div>
    <div class="article-new-field">
      <label class="article-new-detail">写真</label>
        <div class="article-new-detail">
          <%= f.attachment_field :post_img %>
        </div>
    </div>
    <div class="article-new-field">
      <label class="article-new-detail">本文</label>
        <div class="article-new-detail">
          <%= f.text_area :body, class:"form-control", placeholder:"おすすめのパンや、お店の雰囲気など投稿してみましょう！" %>
        </div>
    </div>

    <div class="submit-button">
      <%= f.submit '投稿する', class:"btn btn-primary" %>
    </div>
  <% end %>

app/views/articles/_articles_card.html.erb
  <% articles.each do |article| %>
    <div class="card article-card">
      <%= attachment_image_tag article, :post_img, fallback: "article_no_image.png", size:"150x150", class:"card-img-top" %>
      <div class="card-body">
        <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
        <hr/>
        <p class="card-text">posted by<%= link_to article.user.name, user_path(article.user) %></p>
        <i class="fas fa-bread-slice" aria-hidden="true" style="color: chocolate;">
          <%= article.visits.count %>イッタヨ
        </i>
        <i class="fas fa-plus-square" aria-hidden="true" style="color: tomato;">
          <%= article.interests.count %>キニナル
        </i>
        <p class="card-text"><%= l article.created_at, format: :long %></p>
      </div>
    </div>
    <% end %>

app/views/articles/_comments.html.erb
  <%= form_with(model:[@article, @comment], local: true) do |f| %>
    <%= f.text_area :body, rows:'5',placeholder: "コメントをする（500文字以内）",maxlength:"500", class:"form-control" %>
    <%= f.submit "送信する", class:"btn btn-success" %>
  <% end %>

app/views/articles/edit.html.erb
<div class="contents-header">
  <h1>投稿記事編集</h1>
</div>
<div class="article-form">
  <div class="article-new-field article-form-title">
    <h3>投稿編集</h3>
  </div>
  <%= render 'article_detail' %>
</div>

app/views/articles/index.html.erb
<div class="contents-header">
  <h1>みんなの投稿</h1>
</div>

<div class="article-index-main">
    <article class="article-index">
      <%= render "articles/articles_card",articles: @articles %>
    </article>
      <%= paginate @articles %>
</div>

app/views/articles/new.html.erb
<div class="contents-header">
  <h1>新規投稿</h1>
</div>
<div class="article-form">
  <div class="article-new-field article-form-title">
    <h3>投稿フォーム</h3>
  </div>
  <%= render 'article_detail' %>
</div>

app/views/articles/search_result.html.erb
<div class="contents-header">
  <h1>検索結果</h1>
</div>
<div class="article-index-main">
  <article class="article-index">
    <% if  @search_articles.present? %>
        <% @search_articles.each do |article| %>
        <div class="card article-card">
          <%= attachment_image_tag article, :post_img, fallback: "article_no_image.png", size:"150x150", class:"card-img-top" %>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
        <hr/>
          <p class="card-text"><%= article.body %></p>
        <hr />
          <p class="card-text">posted by<%= link_to article.user.name, user_path(article.user) %></p>
          <i class="fas fa-bread-slice" aria-hidden="true" style="color: chocolate;">
            <%= article.visits.count %>イッタヨ
          </i>
          <i class="fas fa-plus-square" aria-hidden="true" style="color: tomato;">
            <%= article.interests.count %>キニナル
          </i>
          <p class="card-text"><%= l article.created_at, format: :long %></p>
        </div>
        </div>
        <% end %>
    <% else %>
      <h2>検索結果が見つかりません</h2>
    <% end %>
    </article>
      <%= paginate @search_articles %>
</div>

app/views/articles/show.html.erb
<div class="show-main">
  <div class="article-detail">
    <div class="image-show">
      <%= attachment_image_tag @article, :post_img, fallback: "article_no_image.png", size:"300x300" %>
    </div>
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th scope="row" class="badge badge-info">店名</th>
          <td><%= @article.title %></td>
        </tr>
        <tr>
          <th scope="row" class="badge badge-info">評価</th>
          <td><div id="star-<%= @article.id %>"></div>
          </td>
            <!--評価表示-->
          <script>
            $ ('#star-<%= @article.id %>').raty({
              score : '<%= @article.rate %>',
              readOnly :true,
              size : 36,
              starOff :  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf : '<%= asset_path('star-half.png') %>',
              half : true,
            });
          </script>

        </tr>
        <tr>
          <th scope="row" class="badge badge-info">投稿者</th>
          <td><%= link_to @article.user.name, user_path(@article.user) %></td>
        </tr>
        <% if @article.user == current_user %>
        <tr>
          <td></td>
          <td>
            <%= link_to "編集する", edit_article_path(@article), method: :get,class:"btn btn-success" %>
            <%= link_to "削除する", article_path(@article), method: :delete, data: {confirm: "投稿を削除しますか？"}, class:"btn btn-danger" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <hr>

    <article class="card article-body">
      <div class="card-body">
        <p class="article-body">
          <%= @article.body %>
        </p>
        <p class="article-body">
          <%= l @article.created_at, format: :long %>
        </p>
  <hr>

        <div class="article-detail">
          <p class="article-body badge badge-info">
            住所
          </p>
          <p class="article-body">
            <%= @article.address %>
          </p>
        </div>
        <div class="article-map">
          <div id="map" class="gmap"></div>
          <script type="text/javascript">
              function initMap() {
                var test ={lat: <%= @article.latitude %>, lng: <%= @article.longitude %>};
                var map = new google.maps.Map(document.getElementById("map"),
                  { zoom: 15,
                  center: test
                  });
                var transitLayer = new google.maps.TransitLayer();
                  transitLayer.setMap(map);
                var contentString = '住所：<%= @article.address %>';
                var infowindow = new google.maps.InfoWindow({
                  content: contentString
                });
                var marker = new google.maps.Marker({
                            position:test,
                            map: map,
                            title: contentString
                           });
                     marker.addListener('click', function() {
                       infowindow.open(map, marker);
                     });
                  }
          </script>
      </div>

          <hr>
          <div class="article-detail">
            <!--気になるボタン-->
            <div id="interests_button_<%= @article.id %>" class="article-body  article-button">
                <%= render 'interests/interest', locals: { article: @article, interest: @interest } %>
            </div>
            <!--行ったよボタン-->
            <div id="visits_button_<%= @article.id %>" class="article-body  article-button">
                <%= render 'visits/visit', locals: { article: @article, visit: @visit } %>
            </div>
          </div>
          <div id="comments">
            <%= render 'comments/index', comments: @comments %>
          </div>
        </div>
      </article>
    <% if user_signed_in? %>
      <div id="error_explanation">
      </div>
      <div class="new-comment">
        <%= render 'comments/new', comment: @comment, article: @article %>
      </div>
    <% end %>

      <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
      </script>
  </div>