config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  resources :users, except: [:new, :create, :destroy] do
    collection do
      get '/confirm_unsubscribe' => 'users#unsubscribe', as: '/confirm_unsubscribe'
      patch '/withdraw' => 'users#withdraw', as: '/withdraw'
      get :interests
    end
     member do
      get :following, :followers, :timeline
    end

  end

  resources :relationships, only: [:create, :index, :destroy]

  resources :articles do
    resources :comments, only: [:create, :destroy]
    resources :interests, only: [:create, :destroy]
    resource :visits, only: [:create, :destroy]
    collection do
      get :search_result
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 attachment :profile_img

 has_many :articles, dependent: :destroy
 has_many :comments, dependent: :destroy
 has_many :interests, dependent: :destroy
 has_many :interests_articles, through: :interests, source: :article
 has_many :visits, dependent: :destroy

 validates :introduction, length: { maximum: 50 }

 #following機能について
# フォロ-
 has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
 has_many :following, through: :following_relationships
# フォロワー
 has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
 has_many :followers, through: :follower_relationships

 #フォローしているかを確認
 def following?(user)
   following_relationships.find_by(following_id: user.id)
 end

 #フォローメソッド
def follow(user)
  following_relationships.create!(following_id: user.id)
end

 #アンフォローメソッド
 def unfollow(user)
   following_relationships.find_by(following_id: user.id).destroy
 end

 #すでに「気になる」「行ったよ」押している
 def already_interested?(article)
   self.interests.exists?(article_id: article.id)
 end

 def already_visited?(article)
   self.visits.exists?(article_id: article.id)
 end

#退会済みのユーザーのログインをさせない
 def active_for_authentication?
   super && (self.is_deleted == false)
 end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @articles = @user.articles
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(current_user)
  end

  def interests
    @user = current_user
    @articles = current_user.interests_articles
  end

  def unsubscribe
    @user = current_user
  end

  def withdraw
    @user = current_user
    @user.id = current_user.id
    if @articles = Article.find_by(user_id: @user.id)
        @articles.destroy
    end
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  def timeline
    @user = User.find(params[:id])
    @users = @user.following
    @articles = Article.where(user_id: [current_user.id, *current_user.following_ids]).order(created_at: :desc)
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

private

  def user_params
    params.require(:user).permit(:name, :profile_img, :introduction, :is_deleted)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<!--フォローボタン-->
<%= form_with url: relationships_path, remote: true do |f| %>
  <%= f.hidden_field :following_id, :value => @user.id %>
  <div class="profile-detail"><%= f.submit "フォローする", class: "btn btn-outline-secondary" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<!--フォローボタン　ユーザーがサインインユーザーでなければ-->
<% if user_signed_in? && @user != current_user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<!--フォロー解除ボタン-->
<%= form_with url: relationship_path(@user), method: :delete, remote: true do |f| %>
  <div class="profile-detail"><%= f.submit "フォローをやめる", class: "btn btn-outline-secondary" %></div>
<% end %>

app/views/users/_user_show.html.erb
<div  class="profile-main-fixed">
<div class="profile-element-fixed">
  <div class="profile_img">
  <%= attachment_image_tag @user, :profile_img, fallback: "Profile_no_image.png", size: "100x100", class:"rounded-circle"%>
  </div>
</div>
<hr />
<div class="profile-element-fixed">
    <div class="profile-detail-fixed"><%= @user.name %></div>
</div>
<% if @user.id == current_user.id %>
<div class="profile-element-fixed">
    <div class="profile-detail-fixed"><%= link_to "", edit_user_path(current_user.id), class:"btn btn-outline-secondary fas fa-user-cog" %></div>
    <div class="profile-detail-fixed"><%= link_to "", new_article_path, class:"btn btn-outline-secondary far fa-plus-square" %></div>
</div>
</div>
<% end %>

app/views/users/edit.html.erb
<div class="contents-header">
  <h1>プロフィール編集</h1>
</div>
<div class="profile-main profile-edit">
  <%= form_with model:@user, local:true do |f| %>
  <div class="profile-element">
    <label class="profile-detail">プロフィール写真</label>
    <div class="image-show"><%= attachment_image_tag @user, :profile_img, fallback: "Profile_no_image.png", size:"100x100", class:"rounded-circle" %></div>
  </div>
    <div class="image-field"><%= f.attachment_field :profile_img %></div>
  <div class="profile-element">
    <label class="profile-detail">ユーザー名</label>
    <div class="profile-detail">
      <%= f.text_field :name, class:"form-control" %>
    </div>
  </div>
  <div class="profile-element">
    <label class="profile-detail">自己紹介</label>
    <div class="profile-detail">
      <%= f.text_area :introduction, class:"form-control" %>
    </div>
  </div>
  <div class="submit-button">
    <%= f.submit "変更を保存", class:"btn btn-success" %>
    <%= link_to "退会する",confirm_unsubscribe_users_path, class:"btn btn-danger" %>
    <%= link_to "プロフィールに戻る", user_path(@user), class:"btn btn-primary" %>
  </div>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="contents-header">
  <h1>Followers</h1>
</div>
<div class="users-relationships">
  <table class="table table-reflow">
  <tbody>
    <% @user.followers.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_img, fallback: "Profile_no_image.png", size: "50x50", class:"rounded-circle"%></td>
      <td><%= user.name %></td>
      <td><%= link_to "プロフィールを見る", user_path(user), class:"btn btn-outline-info" %></td>
    </tr>
    <% end %>
  </tbody>
  </table>
</div>

app/views/users/following.html.erb
<div class="contents-header">
  <h1>Following</h1>
</div>
<div class="users-relationships">
  <table class="table table-reflow">
  <tbody>
    <% @user.following.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_img, fallback: "Profile_no_image.png", size: "50x50", class:"rounded-circle"%></td>
      <td><%= user.name %></td>
      <td><%= link_to "プロフィールを見る", user_path(user), class:"btn btn-outline-info" %></td>
    </tr>
    <% end %>
  </tbody>
  </table>
</div>

app/views/users/interests.html.erb
<div class="contents-header">
  <h1>気になる一覧</h1>
</div>

<div class="contents-main" >
<%= render "user_show" %>
<div class="contents-bottom">
<%= render "articles/articles_card", articles: @articles %>
</div>
</div>

app/views/users/show.html.erb
<div class="contents-header">
  <h1><%= @user.name %>'s Page</h1>
</div>

<div  class="profile-main">
  <p class="notice"><%= notice %></p>
<div class="profile-element">
  <div class="profile_img">
  <%= attachment_image_tag @user, :profile_img, fallback: "Profile_no_image.png", size: "100x100", class:"rounded-circle"%>
  </div>
    <div class="profile-detail"><%= @user.name %></div>
</div>

<div class="profile-element">
    <label class="profile-detail-introduce">自己紹介</label>
  <div class="profile-detail-introduce"><%= @user.introduction %></div>
</div>

<div class="profile-element">
  <%= link_to "Followers", followers_user_path(@user), class:"profile-detail" %>
  <div class="profile-detail"><%= @user.followers.count %>人</div>
  <%= link_to "Followings", following_user_path(@user), class:"profile-detail" %>
  <div class="profile-detail"><%= @user.following.count %>人</div>
</div>

<% if @user == current_user %>
<div class="profile-element">
    <div class="profile-detail"><%= link_to "プロフィール編集", edit_user_path(current_user.id), class:"btn btn-success fas fa-user-cog" %></div>
    <div class="profile-detail"><%= link_to "新規投稿", new_article_path, class:"btn btn-danger fas fa-plus-circle" %></div>
    <div class="profile-detail"><%= link_to "気になる一覧", interests_users_path, class:"btn btn-info fas fa-bars" %></div>
    <div class="profile-detail" class:"btn btn-outline-secondary fas fa-list"></div>
</div>
<% else %>
  <div class="profile-element">
    <%= render "follow_form" %>
  </div>
<% end %>

  <div class="article-index">
    <%= render "articles/articles_card", articles: @articles %>
  </div>

</div>

app/views/users/timeline.html.erb
<div class="contents-header">
  <h1>フォローしているユーザーの投稿</h1>
</div>
<section class="article-index">
<%= render "articles/articles_card",articles: @articles %>
</section>

app/views/users/unsubscribe.html.erb
<div class="unsubscribe-box">
  <div class="unsubscribe">
  <p>本当に退会しますか？</br>
     これまで投稿した記事や、コメントも消えてしまいます
  </p>
  </div>
  <div class="unsubscribe-button">
    <div class="unsubscribe-button"><%= link_to "退会する",withdraw_users_path, method: :patch, class:"btn btn-outline-danger" %></div>
    <div class="unsubscribe-button"><%= link_to "やっぱりやめる", user_path(current_user), class:"btn btn-outline-success" %></div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/users/withdraw.html.erb
<h1>Users#withdraw</h1>
<p>Find me in app/views/users/withdraw.html.erb</p>