config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  resources :users, except: [:new, :create, :destroy] do
    collection do
      get '/confirm_unsubscribe' => 'users#unsubscribe', as: '/confirm_unsubscribe'
      patch '/withdraw' => 'users#withdraw', as: '/withdraw'
      get :interests
    end
     member do
      get :following, :followers, :timeline
    end

  end

  resources :relationships, only: [:create, :index, :destroy]

  resources :articles do
    resources :comments, only: [:create, :destroy]
    resources :interests, only: [:create, :destroy]
    resource :visits, only: [:create, :destroy]
    collection do
      get :search_result
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/interest.rb
class Interest < ApplicationRecord
  belongs_to :user
  belongs_to :article
  
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    @interest = current_user.interests.new(article_id: params[:article_id])
    @interest.save
  end

  def index
    @interests = Interest.all
  end

  def destroy
    @article = Article.find(params[:article_id])
    @interest = Interest.find_by(user_id: current_user.id, article_id: @article.id)
    @interest.destroy
  end


end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/views/interests/_interest.html.erb
  <% if user_signed_in? %>
    <% if current_user.already_interested?(@article) %>
      <%= link_to article_interest_path(@article, @interest), method: :delete, remote: true do %>
        <i class="fas fa-plus-square" aria-hidden="true" style="color: tomato;">
          <%= @article.interests.count %>キニナル
        </i>
    <% end %>
  <% else %>
    <%= link_to article_interests_path(@article), method: :post, remote: true do %>
      <i class="fas fa-plus-square" aria-hidden="true" style="color: darkgray;">
        <%= @article.interests.count %>キニナル
      </i>
    <% end %>
  <% end %>
  <% else %>
    <i class="fas fa-plus-square" aria-hidden="true" style="color: tomato;">
      <%= @article.interests.count %>キニナル
    </i>
  <% end %>

app/views/interests/create.js.erb
$('#interests_button_<%= @article.id %>').html("<%= j(render 'interests/interest', locals: {article: @article, interest: @interest }) %>");

app/views/interests/destroy.js.erb
$('#interests_button_<%= @article.id %>').html("<%= j(render 'interests/interest', locals: {article: @article, interest: @interest }) %>");